### ISSUE TITLE
Support Revision information as Environment Variables (like Jenkins)

### ISSUE THREAD

**Issue by vitkud** [scm4j/scm4j-releaser#37]
Create/modify env. variable SVN_REVISION before building.
Additionally: GIT_COMMIT, SVN_URL, GIT_BRANCH

**Comment by host6** [comment]
Values?

**Comment by vitkud** [comment]
corresponding to the names

**Comment by host6** [comment]
RootComp depends on LibComp. Which value should have SVN_REVISION var after components tree building: releated to Root or Lib?

**Comment by host6** [comment]
Jenkins exports SVN_REVISION_n and SVN_URL_n env vars where n is number of component

**Comment by maxim-ge** [comment]
Did not get it can somebody explain?

**Comment by host6** [comment]
Save current revision as env var value right before the build. This value could be used by build script.
Suggest following builder description:
```yaml
  builder: 
    cmdLine: cmd /c gradlew.bat uploadArchives
    envVars:
      revision: SVN_REVISION
      url: SVN_URL
      branch: GIT_BRANCH
```
Keep simple builder description: 
```yaml
  builder: cmd /c gradlew.bat uploadArchives
