### ISSUE TITLE
Get rid of !!omap prepending. Check for LinkedHashMap is returned instead

### ISSUE THREAD

**Issue by host6** [scm4j/scm4j-releaser#43]
#9

**Comment by host6** [comment]
Following yaml is errored:
```yaml
!!omap
- eu\.untill\.sdk:untill-driver-api:
   url: http://offsw7.local/svn/untill-driver-api
   type: svn
  123:
   url: http://offsw7.local/svn/123
   type: 123
```
